# Generated by Django 4.0.5 on 2022-06-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='registeruser',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='password2',
            field=models.TextField(default=models.TextField()),
        ),
    ]
